name: Manual Versioning and Publish

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: "Type of version increment (patch, minor, major)"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  version-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'
        registry-url: 'https://registry.npmjs.org/'

    - name: Install dependencies
      run: npm ci

    - name: Bump version
      id: bump_version
      run: |
        npm version ${{ github.event.inputs.version_type }}
        echo "VERSION=$(node -p \"require('./package.json').version\")" >> $GITHUB_ENV
        echo "PREV_VERSION=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo 'v0.0.0')" >> $GITHUB_ENV

    - name: Push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git push origin main --tags

    - name: Publish to NPM
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npm publish

    - name: Create GitHub Release
      uses: actions/create-release@v1
      with:
        tag_name: "${{ env.VERSION }}"
        release_name: "${{ env.VERSION }}"
        body: |
          Release for version v${{ env.VERSION }}.
          
          [View changes](https://github.com/${{ github.repository }}/compare/${{ env.PREV_VERSION }}...v${{ env.VERSION }})
        draft: false
        prerelease: false
        generate_release_notes: false
        token: ${{ secrets.GITHUB_TOKEN }}
